name:Javascript 
on:
  push:
    branches:["mubashira"]
jobs:
  js:
    run-on:ubuntu-latest
    steps:
      name: Checkout Repository
      uses: actions/checkout@v4
      name: Setup Node.js
      uses: actions/setup-node@v4
      name: install dependancy
      uses: npm install 
      name: running file
      uses: npm intern.js
        