name: Javascript 
on:
  push:
    branches: [mubashira]
jobs:
  js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: install dependancy
        run: npm install 
      - name: running file
        run: node intern.js
        